import { Inter } from "next/font/google";
import "./globals.css";
import Navber from '@/components/navber/Navber'
import Mininav from '@/components/movilenav/Mininav'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout_container" >
          <Navber />
           {children}
           <Mininav />
        </div>
       
        </body>
    </html>
  );
}
