import { Inter } from "next/font/google";
import "./globals.css";

import Mininav from '@/components/movilenav/Mininav'
import Navber from "@/components/webnav/Navber";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/Context/AuthProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="layout_container" >
           
            {children}
        
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
